#!/bin/bash


while getopts ":vh:" option
do
 case $option in
  h)
   echo ""
   echo "Usage  : $0 [-vh]"
   echo ""
   echo "option :"   
   echo "          -v  verbose"
   echo "          -h  help"
   echo ""
   exit -1
   ;;
  v)
   v=1
   ;;
 esac
done
if [ -f /etc/default/ssl ];
then
	. /etc/default/ssl
else

	echo "Please enter the name of your cnf files, followed by [ENTER]:"
	read CONFIG
	echo "CONFIG=${CONFIG}" >>/etc/default/ssl
	echo "Please enter the path for your ssl files, followed by [ENTER]:"
	read PATH_SSL
	echo "PATH_SSL=${PATH_SSL}" >>/etc/default/ssl 
	echo "Please enter the IP or FQND of your Ipsec server, followed by [ENTER]:"
	read CN
	echo "CN=${CN}" >>/etc/default/ssl
	echo "Please enter the name of your Organisation, followed by [ENTER]:"
	read Org
	echo "ORGANISATION=${Org}" >>/etc/default/ssl
	echo "New Server Ipsec : `hostname` press [ENTER] to confirm."
	read SRV_IPSEC
	if [[ "$SRV_IPSEC" == "" ]];then
		echo "SRV_IPSEC=`hostname`">>/etc/default/ssl
	else
		echo "SRV_IPSEC=${SRV_IPSEC}">>/etc/default/ssl
	fi
	echo "BITS=8192">>/etc/default/ssl
fi
CONFIG=openssl.cnf
if [[ "$v" == "1" ]]; then
	echo "Mise en place des répertoires  ${PATH_SSL}/{root,web_ca,ipsec} et des fichiers ${PATH_SSL}/{root,web,ipsec}/{index.db,serial}."
fi
rm -fR ${PATH_SSL}/{root,web_ca,ipsec}
mkdir -p ${PATH_SSL}/{ipsec,root,web}/{certs,crl,newcerts,private}
chmod -R 600 ${PATH_SSL}/{root,ipsec,web}/private
touch ${PATH_SSL}/{root,web,ipsec}/{index.db,serial}
sed -i -e 's/^commonName_default.*$/commonName_default                = '${ORGANISATION}' Certification Authority/g'  ${PATH_SSL}/${CONFIG}
sed -i -e 's/^organizationalUnitName_default.*$/organizationalUnitName_default    = Secure Digital Certificate Signing/g'  ${PATH_SSL}/${CONFIG}
if [[ "$v" == "1" ]]; then
	echo "Création de la clé privée pour [ROOT]..."
	echo "openssl req -x509 -config ${PATH_SSL}/${CONFIG} -newkey rsa:${BITS} -sha256 -extensions ROOT_CA -days 3650 -keyout ${PATH_SSL}/root/private/ca.key -out ${PATH_SSL}/root/certs/ca.pem"
fi
openssl req -x509 -config ${PATH_SSL}/${CONFIG} -newkey rsa:${BITS} -sha256 -extensions ROOT_CA -days 3650 -keyout ${PATH_SSL}/root/private/ca.key -out ${PATH_SSL}/root/certs/ca.pem
chmod 400 ${PATH_SSL}/root/private/ca.key
chmod 444 ${PATH_SSL}/root/certs/ca.pem
if [[ "$v" == "1" ]]; then
	echo "Initialisation du serial pour ${PATH_SSL}/root/certs/ca.pem."
	echo "openssl x509 -serial -noout -in ${PATH_SSL}/root/certs/ca.pem | cut -d= -f2 > ${PATH_SSL}/root/serial"
fi
openssl x509 -serial -noout -in ${PATH_SSL}/root/certs/ca.pem | cut -d= -f2 > ${PATH_SSL}/root/serial
