#!/bin/bash
while getopts ":vh:" option
do
 case $option in
  h)
   echo ""
   echo "Usage  : $0 [-vh]"
   echo ""
   echo "option :"   
   echo "          -v  verbose"
   echo "          -h  help"
   echo ""
   exit -1
   ;;
  v)
   v=1
   ;;
 esac
done
if [ -f /etc/default/ssl ];
then
	. /etc/default/ssl
else
	echo "File $FILE does not exist."
	echo "error exit 1"
	return 1
fi
CONFIG=ipsec.cnf
ROOTCONFIG=openssl.cnf
sed -i -e 's/^commonName_default.*$/commonName_default                = '${ORGANISATION}' Certification Authority for IPSec Service/g'  ${PATH_SSL}/${CONFIG}
sed -i -e 's/^organizationalUnitName_default.*$/organizationalUnitName_default    = Secure Digital Certificate Signing/g'  ${PATH_SSL}/${CONFIG}
if [[ "$v" == "1" ]]; then
	echo "Génération de la clé privé crypté pour [IPSEC_CA]..."
	echo "openssl req -newkey rsa:${BITS} -sha256 -keyout ${PATH_SSL}/ipsec/private/ca.key -out ${PATH_SSL}/ipsec/ca.req  -config ${PATH_SSL}/${CONFIG}"
fi
openssl req -newkey rsa:${BITS} -sha256 -keyout ${PATH_SSL}/ipsec/private/ca.key -out ${PATH_SSL}/ipsec/ca.req  -config ${PATH_SSL}/${CONFIG}

if [[ "$v" == "1" ]]; then
	echo "Signature du certificat d'autorité par [ROOT_CA]."
	echo "openssl ca -extensions IPSEC_CA -in ${PATH_SSL}/ipsec/ca.req -out ${PATH_SSL}/ipsec/ca.pem -config ${PATH_SSL}/${CONFIG}"
fi
openssl ca -extensions IPSEC_CA -in ${PATH_SSL}/ipsec/ca.req -out ${PATH_SSL}/ipsec/certs/ca.pem -config ${PATH_SSL}/${ROOTCONFIG}
cat  ${PATH_SSL}/root/certs/ca.pem > ${PATH_SSL}/ipsec/certs/ca-chain.pem
cat  ${PATH_SSL}/ipsec/certs/ca.pem >> ${PATH_SSL}/ipsec/certs/ca-chain.pem
chmod 444  ${PATH_SSL}/ipsec/certs/ca-chain.pem
chmod 400 ${PATH_SSL}/ipsec/private/ca.key
chmod 444 ${PATH_SSL}/ipsec/certs/ca.pem
if [[ "$v" == "1" ]]; then
	echo "Génèration du serial pour ${PATH_SSL}/ipsec/ca.pem."
	echo "openssl x509 -serial -noout -in ${PATH_SSL}/ipsec/ca.pem | cut -d= -f2 > ${PATH_SSL}/ipsec/serial"
fi
openssl x509 -serial -noout -in ${PATH_SSL}/ipsec/certs/ca.pem | cut -d= -f2 > ${PATH_SSL}/ipsec/serial
if [[ "$v" == "1" ]]; then
	echo "TODO"
	echo
	echo
	echo "On peut maintenant créer des certificats client/serveur et les signer avec notre autorité intermédiaire."
	echo # FIN IPSEC_CA
fi
