#!/bin/bash

CONFIG=ipsec.cnf

while getopts ":vh:" option
do
	case $option in
		h)
			echo ""
			echo "Usage  : $0 [-vh]"
			echo ""
			echo "option :"   
			echo "          -v  verbose"
			echo "          -h  help"
			echo ""
			exit -1
			;;
		v)
			v=1
			;;
	esac
done

if [ -f /etc/default/ssl ];
then
	. /etc/default/ssl
else
	echo "File $FILE does not exist."
	echo "error exit 1"
	return 1
fi


sed -i -e 's/^DNS.1.*$/DNS.1                             = '${CN}'/g'  ${PATH_SSL}/ipsec.cnf
sed -i -e 's/^commonName_default.*$/commonName_default                = '${CN}'/g'  ${PATH_SSL}/${CONFIG}
sed -i -e 's/^organizationalUnitName_default.*$/organizationalUnitName_default    = Certificat Hote IPSec/g'  ${PATH_SSL}/${CONFIG}

if [[ "$v" == "1" ]]; then
	echo "Génération de la clé privé crypté pour ${SRV_IPSEC}..."
	echo "openssl genrsa  -out ${PATH_SSL}/ipsec/private/${SRV_IPSEC}.key 4096  -config ${PATH_SSL}/${CONFIG}"
fi
openssl genrsa  -out ${PATH_SSL}/ipsec/private/${SRV_IPSEC}.key 4096  -config ${PATH_SSL}/${CONFIG}

if [[ "$v" == "1" ]]; then
	echo "Création de la clé publique..."
	echo "openssl req -key ${PATH_SSL}/ipsec/private/${SRV_IPSEC}.key -sha256 -out ${PATH_SSL}/ipsec/${SRV_IPSEC}.req -new -nodes -config ${PATH_SSL}/${CONFIG}"
fi

openssl req -key ${PATH_SSL}/ipsec/private/${SRV_IPSEC}.key -sha256 -out ${PATH_SSL}/ipsec/${SRV_IPSEC}.req -new -nodes -config ${PATH_SSL}/${CONFIG}

if [[ "$v" == "1" ]]; then
	echo "Signature du certificat [HOTE] par l'autorité [IPSEC]." 
	echo "Notre certificat Hôte aura l'extentions serverAuth signalés dans la section [HOTE]."	
	echo "openssl ca -name IPSEC -extensions HOTE -in ${PATH_SSL}/ipsec/${SRV_IPSEC}.req -out ${PATH_SSL}/ipsec/certs/${SRV_IPSEC}.pem -config  ${PATH_SSL}/${CONFIG}"
fi

openssl ca -name IPSEC -extensions HOTE -in ${PATH_SSL}/ipsec/${SRV_IPSEC}.req -out ${PATH_SSL}/ipsec/certs/${SRV_IPSEC}.pem -config  ${PATH_SSL}/${CONFIG}

chmod 400 ${PATH_SSL}/ipsec/private/${SRV_IPSEC}.key
chmod 444 ${PATH_SSL}/ipsec/certs/${SRV_IPSEC}.pem
