#!/bin/bash -x

if [ -f /etc/default/ssl ];
then
	. /etc/default/ssl
else
	echo "File $FILE does not exist."
	echo "error exit 1"
	return 1
fi

echo "Nom du client:"
read CLIENT
echo 
echo 

echo $((`wc -l /var/ipfire/vpn/config | awk '{ print $1}'`+1)),off,${CLIENT},CN=${CLIENT}.${CN} OU=Certificat Acces IPSec,host,cert,,,,0.0.0.0/0,,,172.16.0.0/24,,,,,,,,,,,,,,,,,,,,>>/var/ipfire/vpn/config








cat <<EOF > /var/ipfire/vpn/settings 
ENABLED=off
ROOTCERT_OU=Secure Digital Certificate Signing
ROOTCERT_EMAIL=
ROOTCERT_HOSTNAME=${ORGANISATION} Intermediate Certification Authority for IPSec Service
ROOTCERT_CITY=
ROOTCERT_STATE=
ROOTCERT_COUNTRY=FR
ROOTCERT_ORGANIZATION=${ORGANISATION}
VPN_DELAYED_START=0
EOF

cat << EOF > /var/ipfire/vpn/caconfig
1,ROOTCA,C=FR O=${ORGANISATION}  OU=Secure Digital Certificate Signing  CN=${ORGANISATION} Certification Authority
EOF

rm /var/ipfire/certs/hostcert.pem
rm /var/ipfire/certs/hostkey.pem
rm /var/ipfire/ca/cacert.pem
rm /var/ipfire/ca/ROOTCAcert.pem
rm /var/ipfire/private/cakey.pem

ln -s /etc/ssl/ipsec/ipfire.pem /var/ipfire/certs/hostcert.pem
ln -s /etc/ssl/ipsec/private/ipfire.key /var/ipfire/certs/hostkey.pem
ln -s /etc/ssl/ipsec/ca.pem /var/ipfire/cacert.pem
ln -s /etc/ssl/root/ca.pem /var/ipfire/ca/ROOTCAcert.pem
ln -s /etc/ssl/ipseca/private/ca.key /var/ipfire/private/cakey.pem

wget https://raw.githubusercontent.com/jbsky/ipfire-2.x/84e2a906a5c102605179edf731efa793f56e38b1/html/cgi-bin/vpnmain.cgi
wget https://raw.githubusercontent.com/jbsky/ipfire-2.x/84e2a906a5c102605179edf731efa793f56e38b1/html/cgi-bin/connections.cgi
chmod +x *.cgi
mv *.cgi /srv/web/ipfire/cgi-bin/ 
# echo $((`wc -l ${PATH_INSTALL}/vpn/config | awk '{ print $1}'`+1)),off,${NOM_CLIENT},CN=${NOM_CLIENT}.${NOM_DOMAINE} OU=Client VPN,host,cert,,,,${NET_GREEN},,,${IP_VPN_CLIENT}/32,,,,,,,,,,,,,,,,,,,,>>${PATH_INSTALL}/vpn/config
