#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          samba
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Samba initscript
# Description:
### END INIT INFO

#
if [ ! -d /usr/bin ]; then
	echo "The /usr file system is not mounted."
        exit 1
fi

killproc() {
        pid=`/bin/ps ax | grep -w $1 | sed -e 's/^  *//' -e 's/ .*//'`
	echo "Stopping $1 now."
        [ "$pid" != "" ] && kill -15 $pid
	echo $pid
}


# Start/stop processes required for samba server

case "$1" in

	'start')
	   echo "Starting Samba"
	   /usr/sbin/samba
	   echo "Done."
	   ;;
	'stop')
	   killproc samba
	   ;;
	*)
	   echo "Usage: /sbin/init.d/samba [ start | stop ]"
	   ;;
esac
exit 0
